### ISSUE TITLE
English Homepage

### ISSUE THREAD

**Issue by developerppv** [tossdev/tossdev.github.io#10]
Hi, is there any plan to provide english translation on your website?
I am interested in using your service, but only know little about korean language.
Thanks.

**Comment by tossdev** [comment]
Hi, First of all thank you for using our service.

We already have an English homepage.

The homepage address is [ https://toss.im/en /]

I hope this homepage will help you.

Thank you.

*Toss 서비스팀*

*Viva Republica** | *toss.im

1599-4905  | 카카오톡: @toss



2018-08-10 10:35 GMT+09:00 Coinmore Developer <notifications@github.com>:

**Comment by developerppv** [comment]
How about developer homepage?
I mean this one: http://tossdev.github.io
Cheers.
