### ISSUE TITLE
feature request: language-specific API

### ISSUE THREAD

**Issue by jeehoonkang** [tossdev/tossdev.github.io#2]
Currently Toss API requires users to access the server via an HTTPS request.  For e.g. in Python users need to use the generic `urllib` library (or equivalent) to access the server.

I wonder if you have a plan to release a language-specific API to access the Toss server.  Note that Paypal supports it: for e.g. see https://developer.paypal.com/docs/api/payments/#authorization and https://github.com/paypal/PayPal-Python-SDK/blob/master/samples/authorization/find.py .

**Comment by jeehoonkang** [comment]
Not related to this topic, but I also wonder if this issue tracker is the right communication channel for a feature request.  Please advise me if it is not.

**Comment by tossdev** [comment]
안녕하세요. 토스팀입니다.
토스 결제 API 서비스에 관심을 가지고 의견 주셔서 감사합니다. 제안해주신 기능은 개발 백로그에 추가하여 지원할 수 있도록 하겠습니다. 정확한 제공 시점을 말씀드리기 어려운 점은 양해 부탁드립니다. 감사합니다.
- 이 채널을 통해 제안을 받는 것은 저희도 미쳐 생각지 못한 부분입니다만, 매우 좋은 것 같습니다. 이에 대해서도 감사드립니다. 😄
