### ISSUE TITLE
feature request: API versioning

### ISSUE THREAD

**Issue by jeehoonkang** [tossdev/tossdev.github.io#3]
- Is the current API in the 1.0 status?  Or in other words, do you commit to the current API for a significant period of time (e.g. 5 years)?
- Is it possible that API can change in the future?  If so, what is the versioning scheme for the API?

**Comment by tossdev** [comment]
현재 API는 1.0 상태이며, 버전 변경은 예정되어있지 않습니다.

추후 버전 변경이 생긴다면, 아래와 같은 형태로 변경될 예정입니다.
https://toss.im/tosspay/api/v1/payments
https://toss.im/tosspay/api/v2/payments
https://toss.im/tosspay/api/v3/payments
...
