### ISSUE TITLE
call for clarification: Error code of incorrect API key for several API methods

### ISSUE THREAD

**Issue by jeehoonkang** [tossdev/tossdev.github.io#4]
What is the error code of the incorrect API key for (POST) `https://toss.im/tosspay/api/v1/payments`, (POST) `https://toss.im/tosspay/api/v1/execute`, and (POST) `https://toss.im/tosspay/api/v1/refunds/{refundNo}`?

(See: http://tossdev.github.io/api.html)

**Comment by tossdev** [comment]
위 3가지 API 요청 시, API Key가 올바르지 않은 경우, 아래와 같이 처리됩니다.

-> 코드 -1
-> 에러 사유를 msg로 알려줌 ("올바르지 않은 API key입니다.")

**Comment by jeehoonkang** [comment]
다른 method들은 해당 에러 코드가 1번인데, 세 method만 -1이랑 말씀이시군요..  다소 비직관적이라고 생각합니다만 이해할 수 있는 결정이라 생각합니다.  감사합니다.

**Comment by jeehoonkang** [comment]
- 혹시 documentation에 업데이트해주실 수 있으십니까?

**Comment by tossdev** [comment]
답변이 늦어 죄송합니다.
위 사항을 포함하여 문서 업데이트를 준비하고 있습니다. 업데이트 되는대로 추가로 코멘트를 남기도록 하겠습니다.

감사합니다.
