### ISSUE TITLE
call for clarification: SLA for server up-time and security

### ISSUE THREAD

**Issue by jeehoonkang** [tossdev/tossdev.github.io#5]
- How much extent do you guarantee the server up-time?
- How secure is the API key?  More concretely, what is the entropy level of the API keys?

**Comment by tossdev** [comment]
Toss 결제 서비스는 은행 계좌 기반의 결제로 각 은행의 점검시간 동안에는 서비스가 일시적으로 중지됩니다. 각 은행의 점검시간은 아래 문서를 참고해주시기 바랍니다.
http://tossdev.github.io/api.html#maintenance

API Key에 대해서는 어떤 점을 우려하시는지 알려주실 수 있을까요?

**Comment by jeehoonkang** [comment]
- 각 은행 점검시간 외에는 toss 서버가 항상 살아있다고 보장하십니까?  혹여 그렇지 못한 경우 어떤 보상을 해주실 예정이십니까?

결제 관련 api다보니 다른 api보다 다소 깐깐하게 따져보게 됩니다.  귀찮게 해드려 죄송합니다..

**Comment by jeehoonkang** [comment]
Api key를 공격자가 추측해서 api call을 하는 경우, 어떤 확률로 공격에 성공할까요?
