### ISSUE TITLE
송금 요청 API 관련

### ISSUE THREAD

**Issue by webhacking** [tossdev/tossdev.github.io#6]
송금 요청 당 발생하는 `비용`과 `소요시간`이 어찌되나요 ?
추가로 1초내에 `3000`건 정도의 송금 요청을 한다고 가정한다면 토스 서버측에서 따로 요청을 막는다거나 조치를 취하나용 ❔

**Comment by tossdev** [comment]
안녕하세요! 문의 주셔서 감사합니다.

이체대행 API는 실제 송금을 요청하는 '이체 API'와 보내기 전 예금주를 확인하는 '예금주 조회 API'로 구성되어 있습니다. 이체는 성공 건당 200원, 예금주 조회는 건당 40원이 부과됩니다. (부가세 별도)

입금까지 소요되는 시간은 은행망의 상태에 따라 약간의 차이가 있으나 일반적으로 1초 이내입니다.

이체 요청은 초당 4건까지만 가능합니다.

추가로 현재 이체대행 서비스는 신규 가입을 받지 않고 있음을 알려드립니다. 

감사합니다.
